#Values are base 64 encoded and will be decoded automatically by kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
  DB_USERNAME: YWRtaW4=
  DB_PASSWORD: MWYyZDFlMmU2N2Rm